#!/bin/bash

ORIGINAL_DIRECTORY="original"
THUMBNAIL_DIRECTORY="thumbnail"
THUMBNAIL_WIDTHS_PIXEL=( 200 650 )

for FILE in $(ls $ORIGINAL_DIRECTORY/*.png $ORIGINAL_DIRECTORY/*.jpg); do
	ORIGINAL_BASENAME=$(basename "${FILE}")

	# @see http://stackoverflow.com/a/965072
	ORIGINAL_NAME="${ORIGINAL_BASENAME%.*}"
	ORIGINAL_EXTENSION="${ORIGINAL_BASENAME##*.}"


	for THUMBNAIL_WIDTH_PIXEL in "${THUMBNAIL_WIDTHS_PIXEL[@]}"; do
		convert -scale "${THUMBNAIL_WIDTH_PIXEL}" "${FILE}" "${THUMBNAIL_DIRECTORY}/${ORIGINAL_NAME}-${THUMBNAIL_WIDTH_PIXEL}.${ORIGINAL_EXTENSION}"
	done
done

