#!/bin/bash

ORIGINAL_DIRECTORY="original"
THUMBNAIL_DIRECTORY="thumbnail"
THUMBNAIL_WIDTH_PIXEL="200"

for IMAGE in $(ls $ORIGINAL_DIRECTORY/*.png $ORIGINAL_DIRECTORY/*.jpg); do
	IMAGE_NAME=$(basename "${IMAGE}")
	convert -scale "${THUMBNAIL_WIDTH_PIXEL}" "${ORIGINAL_DIRECTORY}/${IMAGE_NAME}" "${THUMBNAIL_DIRECTORY}/${IMAGE_NAME}"
done

